#  application.yaml работает в jvm и native, но не работает в режиме сервлета с Tomcat
# в этом случае необходимо сформировать application.conf

ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - com.crowdproj.ad.app.swagger.ApplicationKt.module
  urls:
    - "http://0.0.0.0:8081/"
    - "http://127.0.0.1:8081/"
    - "http://localhost:8081/"
    - "http://192.168.0.182:8081/"
