version: '3'

services:
  app:
    image: crowdproj-ad-app-ktor-x64:latest  # Replace with your actual microservice image and tag
#    ports:
#      - "8080:8080"
    volumes:
      - ./app/certs:/app/certs  # Mount your TLS certificates
    networks:
      - my_network

  envoy:
    image: envoyproxy/envoy:v1.29.0  # Use the official Envoy proxy image
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml  # Mount your Envoy configuration file
#      - ./envoy/certs:/etc/envoy/certs  # Mount your TLS certificates
    ports:
      - "15001:15001"
      - "8090:8090"
    networks:
      - my_network

  keycloak:
#    image: jboss/keycloak:latest
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
      - "8082:9990"
    volumes:
#      - ./keycloak:/tmp
      - ./keycloak/import:/opt/keycloak/data/import
    #      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    #      - ./keycloak/certs/keycloak.jks:/etc/x509/https/keystore  # Mount your Keycloak keystore
    environment:
      KEYCLOAK_USER: otus
      KEYCLOAK_PASSWORD: otus
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
    command:
      - start-dev
#      - --features admin-fine-grained-authz
      - --import-realm
    networks:
      - my_network

networks:
  my_network:
#    external: true
