ktor:
  development: false
  deployment:
    port: "$PORT:8080"
#  watch:
#    - classes
#    - resources
  application:
    modules:
      - com.crowdproj.ad.app.ApplicationKt.module
  urls:
    - "$APP_URL:http://0.0.0.0:8080/"
    - "$APP_URL_1:"
    - "$APP_URL_2:"
